-- AlterTable BrokerAccount
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "statusMessage" TEXT;
ALTER TABLE "BrokerAccount" ADD COLUMN IF NOT EXISTS "metaApiRegion" TEXT DEFAULT 'new-york';

-- AlterTable StrategyConfig — SuperMeta DCA fields
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "symbol" TEXT NOT NULL DEFAULT 'EURUSD';
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "direction" TEXT NOT NULL DEFAULT 'BUY';
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "entryCount" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "entryMultiplier" DOUBLE PRECISION NOT NULL DEFAULT 2;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "entryIntervalPct" DOUBLE PRECISION NOT NULL DEFAULT 5;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "takeProfitPct" DOUBLE PRECISION NOT NULL DEFAULT 1;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "startLots" DOUBLE PRECISION NOT NULL DEFAULT 0.01;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "repeatEnabled" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "stopLossPct" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "stopLossEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "stopOnSl" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "hedgeEnabled" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "StrategyConfig" ADD COLUMN IF NOT EXISTS "hedgePct" DOUBLE PRECISION NOT NULL DEFAULT 2;
