-- AlterTable: fixed dollar TP/SL (startLots margin × ROI%)
ALTER TABLE "SymbolBot" ADD COLUMN IF NOT EXISTS "takeProfitUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
ALTER TABLE "SymbolBot" ADD COLUMN IF NOT EXISTS "stopLossUsd" DOUBLE PRECISION NOT NULL DEFAULT 0;
